# environment.yml for the Altera Labs backend

name: altera-labs

channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python version
  - python=3.11

  # Web server dependencies from Conda
  - flask
  - flask-cors
  - python-dotenv
  - requests
  - pip

  # Dependencies to install with Pip
  - pip:
      - PyMuPDF
      - pexpect
      - tqdm                   # progress bar for cache download
      - requests_toolbelt      # faster streaming download (optional)