name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Lint Backend
        run: |
          pip install flake8
          flake8 backend

      - name: Verify TypeScript Build
        working-directory: frontend
        run: |
          npm ci
          npm run build --if-present

      - name: Smoke Test Pipeline CLI (import only)
        run: |
          python -c "import backend.pipelines.build_mathlib_graph as m; print('OK')"


